# Generated by Django 5.2 on 2025-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
