# Generated by Django 5.2 on 2025-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_foodmenu_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
